language: ruby
rvm:
  - 2.2.1

# dist: precise

env:
  - ES_TEST_HOST=localhost ES_TEST_PORT=9250 ES_TEST_BIN=elasticsearch SUBMISSION_DUE_DATE='July 8 2015 23:59 UTC-3' ACCEPTANCE_DUE_DATE='August 17 2015 23:59 UTC-3' DISPLAY=:99 NODE_PATH=$NODE_PATH:/home/travis/.nvm/v0.10.36/lib/node_modules

addons:
  postgresql: "9.3"

services:
  - elasticsearch

#   apt:
#     packages:
#       - oracle-java8-set-default

before_install:
#   - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.2.deb && sudo dpkg -i --force-confnew elasticsearch-5.1.2.deb && sudo service elasticsearch start
  - curl -v http://localhost:9200/

# config/database.yml in Rails
test:
  adapter: postgresql
  database: open_call_test
  username: postgres

cache:
  bundler: true
  directories:
    - node_modules

before_script:
  - psql -c 'create database open_call_test;' -U postgres
  - bundle exec rake db:migrate RAILS_ENV="test"
  # - bundle exec rake protractor:install
  # - npm install -g coffee-script
  # - sh -e /etc/init.d/xvfb start

script:
  - bundle exec rake
  # - bundle exec rake open_call:e2e

before_deploy:
  - "echo $TRAVIS_COMMIT > public/commit_track.txt"

deploy:
  provider: heroku
  skip_cleanup: true
  run: 
    - "rake db:migrate"
  api_key:
    secure: uYBMPaMvVmNxZadZn80bBEU1LG4HgvlDO7gYOwE0whLvsrsfZH7xsNa1QQCgUFyk/b0x71WSaB1VmeWAhVeI5CnLotQRvhcD1G1ytY6a81sByIyS48UUGFOZwV2uVNyeOxvDifJ3GrtCHMmfjkBmqZHd+SyAxRH9itqGvCLP240=
  app:
    develop: opencallstage
    master: opencall
